### ISSUE TITLE
build file misses dependency from plugin to agent module

### ISSUE THREAD

**Issue by grexe** [sourceplusplus/Assistant#105]
When I want to build the plugin straight away, the build fails, because it has a dependency on the agent module, which is not declared in the build script (but should, as Gradle supports that).

So `./gradlew buildPlugin` fails with
> java.io.FileNotFoundException: /Users/gregor/Develop/Assistant/agent/jvm-agent/build/libs/source-agent-0.2.2.jar (No such file or directory)

but builds fine after
> ./gradlew buildAgent

I'd expect the first build to succeed and build the dependency automatically, which would work in the build file expressed that explicitly.

**Comment by BFergerson** [comment]
@grexe, closing this issue since it should only be present on the ` java-11-upgrade` branch. Still working on that upgrade. I removed it because the JetBrains Runtime doesn't have the "jmods" folder so I was having issues with ProGaurd. Installing Java JDK 11 locally and switching to that works though.
